name: build jsrunner
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  push:
    name: "damagex:jsrunner.codes"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/damagex/damagex:jsrunner.codes
